name: Deploy Serverless Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TF_LOG: INFO
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  TERRAFORM_LOGIN: ${{ secrets.TERRAFORM_LOGIN }}
  ALARM_EMAIL: ${{ secrets.ALARM_EMAIL }}
  SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.5.7
  PYTHON_VERSION: 3.12

permissions:
  contents: read
  id-token: write
  pull-requests: write
  issues: write

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Terraform security scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: false

      - name: Security check - Bandit
        uses: Joel-hanson/bandit-report-artifacts@V1
        with:
          python_version: ${{ env.PYTHON_VERSION }}
          project_path: ./src/
          ignore_failure: true

      - name: Security check report artifacts
        uses: actions/upload-artifact@v4
        # if: failure()
        with:
          name: Security report
          path: output/security_report.txt
  test:
    name: Test
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest boto3

      - name: Run tests
        run: |
          pytest ./src/

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_KEY }}"
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TERRAFORM_LOGIN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Package Lambda functions
        run: |
          cd terraform/src
          zip -j insertStudentData.zip insertStudentData.py
          zip -j getStudents.zip getStudents.py            

      - name: Terraform init
        id: init
        run: |
          cd terraform
          terraform init

      - name: Terraform fmt
        id: fmt
        run: |
          cd terraform
          terraform fmt

      - name: Terraform validate
        id: validate
        run: |
          cd terraform
          terraform validate

      - name: Terraform plan
        id: plan
        if: github.event_name == 'pull_request'
        run: |
            cd terraform
            terraform plan -no-color -input=false
        continue-on-error: true
    
      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd terraform
          terraform apply -auto-approve -input=false

      - name: Send Terraform Output Email
        if: success() && github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          python -m pip install --upgrade pip
          pip install boto3 secure-smtplib
          cd terraform
          python ./scripts/send_terraform_output.py
        env:
          ALARM_EMAIL: ${{ secrets.ALARM_EMAIL }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}