name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm deletion of all resources'
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'destroy'

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      TERRAFORM_LOGIN: ${{ secrets.TERRAFORM_LOGIN }}
      AWS_REGION: us-east-1
      PYTHON_VERSION: 3.12

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 secure-smtplib

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY }}'
        aws-secret-access-key: '${{ secrets.AWS_SECRET_KEY }}'
        aws-region: '${{ env.AWS_REGION }}'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_wrapper: false
        cli_config_credentials_token: ${{ secrets.TERRAFORM_LOGIN }}

    - name: Terraform Destroy
      run: |
        cd terraform
        terraform destroy -auto-approve
      env:
        TF_VAR_alarm_email: ${{ secrets.ALARM_EMAIL }}

    - name: Send Destroy Notification
      if: success()
      run: |
        python -m pip install --upgrade pip
        pip install secure-smtplib
        cd terraform
        python scripts/send_destroy_notification.py
      env:
        ALARM_EMAIL: ${{ secrets.ALARM_EMAIL }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}